# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# Workflow syntax reference:
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: JSII Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # This is used by the SharedProps to detect a PR build
  PR_NUMBER: ${{ github.event.pull_request.number }}
  APP_NAME: release
  APP_PACKAGE_NAME: '@pwrdrvr/microapps-app-release'
  ENV: dev

jobs:
  jsii:
    if: github.event_name != 'pull_request' || (github.event_name == 'pull_request' && contains( github.event.pull_request.labels.*.name, 'BUILD-JSII'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      #
      # Build Construct with JSII
      #

      # JSII does not work well with monorepos
      - name: Move root NPM modules out of the way
        run: mv node_modules node_modules_hide
      - name: Move root package-lock.json out of the way
        run: |
          mv package-lock.json package-lock.json_hide
          mv package.json package.json_hide

      - name: Install CDK Construct Deps
        working-directory: packages/cdk-construct/
        run: |
          npm ci

      - name: Build with JSII
        working-directory: packages/cdk-construct/
        run: |
          npm run build:jsii-all

      - name: Move root NPM modules back
        run: mv node_modules_hide node_modules
      - name: Move root package-lock.json back
        run: |
          mv package-lock.json_hide package-lock.json
          mv package.json_hide package.json

      - name: Confirm No Doc Changes
        working-directory: packages/cdk-construct/
        run: |
          git diff --ignore-space-at-eol --exit-code

    container:
      image: jsii/superchain:1-buster-slim-node16
